USE yongchen;

DROP TABLE IF EXISTS account_info ;

/*账户信息表*/
CREATE TABLE account_info(
id INT(11) AUTO_INCREMENT PRIMARY KEY,
user_id VARCHAR(20) NOT NULL ,
user_pass VARCHAR(20) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


/*用户信息表*/
DROP TABLE IF EXISTS user_info ;

CREATE TABLE user_info(
id INT(11) AUTO_INCREMENT PRIMARY KEY,
account_id INT(11) NOT NULL,
user_name VARCHAR(20) NOT NULL,
age INT(3),
sex INT(2) NOT NULL,
phone BIGINT(20) NOT NULL,
FOREIGN KEY (account_id) REFERENCES account_info(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS role_info;
/*创建角色表*/
CREATE TABLE role_info(
id INT(11) AUTO_INCREMENT PRIMARY KEY,
role_id INT(4) NOT NULL,
role_name VARCHAR(10) NOT NULL,
)ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;








